fix webhooks handler setup and allow customize
solidusio-contrib/solidus_easypost pull request #100
Opened 2021-10-05 06:31 UTC by ccarruitero

2021-11-23 18:38 UTC, ccarruitero commented
ping @aldesantis 

Error in linter is not related to the changes

2021-11-24 08:39 UTC, aldesantis commented
@ccarruitero quick question on this: what's your use case for customizing the webhook handler? The handler already publishes events on the Solidus bus, meaning you can easily hook in your logic by listening to those events, so I'm curious to know what kind of customization you have that's not supported by this model.

2021-11-25 17:01 UTC, ccarruitero commented
Well, in the project I have been working latest months, we have different carriers integrations (across easypost and other custom carriers apis). We have a custom shipment state machine and we don't use cartons. We need to track additional shipments states and preserver first ones, so instead to customize a carton we decide to use only shipments.

Current webhook handler relay on carton use to fire solidus events, but in our use case we are using only shipments. So need to use a custom handler

2021-11-30 08:28 UTC, aldesantis commented
@ccarruitero okay, got it! Could you just update the documentation to reflect that the events will only be fired if you haven't customized your webhook handler?

2021-12-01 00:55 UTC, ccarruitero commented
@aldesantis I updated docs. Let me know what you think

2021-12-01 10:26 UTC, aldesantis requested changes
@ccarruitero just a couple of comments and then it should be good to merge, thanks!

2021-12-01 10:26 UTC, aldesantis commented on README.md
> +### Customizing tracking webhook handler
This should be `Customizing the tracking webhook handler`. 🙏

2021-12-01 10:26 UTC, aldesantis commented on README.md
> +Note that if you override webhook handler, solidus events mentioned above don't be triggered unless your webhook handler class do
Can you change this slightly to the following?

```
Note that, if you override the webhook handler, no events will be fired out of the box.
```

2021-12-01 21:20 UTC, ccarruitero commented
@aldesantis Thanks for your comments. I updated docs

2021-12-02 07:54 UTC, aldesantis approved these changes

2021-12-02 07:54 UTC, merged

2021-12-02 07:54 UTC, aldesantis commented
@ccarruitero thanks for bearing with me on this one, great work!